networks:
  ttc-tops:
    external: true
    name: ttc-tops
    driver: bridge
services:
  rempmm-bot:
    image: sergeiavdeev/rempmm-bot
    container_name: rempmm-bot
    restart: always
    environment:
      spring.profiles.active: ${PROFILE}
    networks:
      - ttc-tops
    deploy:
      resources:
        limits:
          memory: '512M'
        reservations:
          memory: '256M'